use_frameworks!

target 'HTPopoverMenu_Example' do
  pod 'HTPopoverMenu', :path => '../'

  target 'HTPopoverMenu_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
